version: '3'
services:
  app:
    image: docker.io/benjamindutta/emsbackend:latest
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://databaseems.c89l7x16vlfk.us-east-1.rds.amazonaws.com:3306/emsdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=benja123
  frontend:
    image: docker.io/benjamindutta/frontendems:latest
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    depends_on:
      - app
